### ISSUE TITLE
Broken OpenSSL 1.1 support

### ISSUE THREAD

**Issue by ghost** [probonopd/XChat#4]
Got this error while trying to build on Debian 9 :

Result of _./configure_ :
```
xchat 2.8.8

Building GTK+ Interface .... : yes
Building TEXT Interface .... : no

PLUGINS: Perl: yes Python: yes TCL: no

mmx tinting ......... : no	spelling .............. : static
XShm tinting ........ : no	plugin interface ...... : yes
text backend ........ : pango	nls/gettext ........... : yes
openssl support ..... : yes	ipv6 support .......... : no
dbus support ........ : no	msproxy ntlm (ISA) .... : no
libnotify support ... : no
```

The errors :
```
server.c: In function ‘ssl_cb_verify’:
server.c:607:47: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
  X509_NAME_oneline (X509_get_subject_name (ctx->current_cert), subject,
                                               ^~
server.c: In function ‘ssl_do_connect’:
server.c:760:16: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
   if (serv->ssl->session && serv->ssl->session->time + SSLTMOUT < time (NULL))
                ^~
```

**Comment by ghost** [comment]
I'm currently trying to tackle this using [this similar issue](https://github.com/hexchat/hexchat/issues/1759).

**Comment by probonopd** [comment]
OpenSSL 1.1 is not compatible with OpenSSL 1.0. I don't think that XChat supports OpenSSL 1.1 or has plans to do so. OpenSSL 1.0 will continue to be available for the forseeable future.

Enterprise and LTS distirbutions cannot be expected to use OpenSSL 1.1 anytime soon, since it is not a "dot release" as in semantic versioning, but in fact an ABI-breaking major release.

Please see https://github.com/openssl/openssl/issues/5042 for more information.
